### ISSUE TITLE
网站域名

### ISSUE THREAD

**Issue by SilverLeaves** [program-in-chinese/docsSite#3]
网站域名

**Comment by nobodxbodon** [comment]
已有. 详请见 https://github.com/program-in-chinese/team_website 首页说明.

**Comment by SilverLeaves** [comment]
@nobodxbodon 可以给我一个二级域名吗? CNAME指向`coding.chinese.saigao.fun`就好.

**Comment by SilverLeaves** [comment]
JS或TS的中文开发. 慢慢深入. 
没有应用的中文开发语言控油灵魂而没有生命, 希望做点真正有用的东西.
